import Link from 'next/link';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import CookieConsent from '@/components/CookieConsent';
import TrackedCTA from '@/components/TrackedCTA';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  ArrowRight,
  Bot,
  Check,
  CheckCircle,
  Clock,
  Database,
  FileText,
  Mail,
  Route,
  ShieldCheck,
  Workflow,
} from 'lucide-react';

export const metadata = {
  title: 'AI Automation Consulting Canada | n8n & CRM Workflows',
  description:
    'AI automation consulting for n8n, CRM workflows, Gmail drafts, approval gates, lead routing, reporting, and human-reviewed operations.',
  alternates: { canonical: 'https://www.emergent-logic.ca/services/ai-automation-consulting' },
  robots: { index: true, follow: true },
  openGraph: {
    title: 'AI Automation Consulting | Emergent Logic',
    description:
      'AI workflow automation connected to CRM, Gmail, Google Sheets, HubSpot, Salesforce, n8n, and human approval gates.',
    url: 'https://www.emergent-logic.ca/services/ai-automation-consulting',
    images: [{ url: 'https://www.emergent-logic.ca/og-image.png', width: 1200, height: 630 }],
  },
};

const automationTypes = [
  {
    icon: Database,
    title: 'CRM automation',
    desc: 'HubSpot, Salesforce, Zoho, or Google Sheets workflows for lead routing, lifecycle updates, owner assignment, task creation, and reporting.',
  },
  {
    icon: Mail,
    title: 'Draft-first outreach automation',
    desc: 'Prospect intake, segmentation, personalization, Gmail draft creation, blocked-domain checks, and human review before anything gets sent.',
  },
  {
    icon: Workflow,
    title: 'n8n workflow automation',
    desc: 'n8n workflows that connect forms, sheets, CRMs, email, webhooks, APIs, and approval steps into one practical operating process.',
  },
  {
    icon: Bot,
    title: 'AI-assisted operations',
    desc: 'AI summaries, classification, routing suggestions, research notes, content drafts, and follow-up recommendations with clear guardrails.',
  },
  {
    icon: Route,
    title: 'Lead capture and handoff',
    desc: 'Website forms, chatbot conversations, booking requests, and contact submissions routed into the right CRM views and follow-up queues.',
  },
  {
    icon: FileText,
    title: 'Documentation and handoff',
    desc: 'Workflow maps, field definitions, test scenarios, rollback notes, and operator instructions so your team can understand the system.',
  },
];

const processSteps = [
  'Map the manual process, source systems, current bottlenecks, and where human judgment is still required',
  'Define the minimum safe workflow: trigger, data required, decision points, owner, output, and failure path',
  'Clean or create the CRM fields, sheet columns, labels, statuses, and approval properties the workflow needs',
  'Build the first automation in n8n, HubSpot, Salesforce, Zapier, Make, or custom API code depending on fit',
  'Add guardrails: blocked domains, duplicate checks, approval gates, error logs, notifications, and manual override steps',
  'Test with real scenarios before launch, including bad data, duplicates, no-fit records, and missing fields',
  'Document the workflow and train the operator before expanding into the next automation',
];

const goodFit = [
  'You have repeatable manual work that happens every week',
  'You use HubSpot, Salesforce, Zoho, Google Sheets, Gmail, forms, or webhooks',
  'You want AI assistance without giving AI uncontrolled authority',
  'You need CRM records, tasks, notes, and reporting to stay clean',
  'You want n8n or another automation layer built with human approval checkpoints',
  'You would rather automate one process well than build a huge fragile system at once',
];

const notFit = [
  'You want a fully autonomous AI employee with no review or monitoring',
  'Your core process is not defined enough for automation yet',
  'Your CRM data is too messy and needs cleanup first',
  'You need regulated advice generated by AI without human review',
  'You want one-off scripts with no documentation or owner',
];

const faqs = [
  {
    q: 'Do you only build in n8n?',
    a: 'No. n8n is often a strong fit for flexible workflow automation, but we also build inside HubSpot, Salesforce, Zapier, Make, Google Apps Script, and custom API workflows when those are better fits.',
  },
  {
    q: 'Can AI send emails automatically?',
    a: 'Technically yes, but we usually recommend draft-first automation for outbound. AI can research, personalize, and draft. A human should review before sending until sender identity, data quality, and messaging are proven.',
  },
  {
    q: 'What should we automate first?',
    a: 'Start with one high-frequency, low-risk process: website lead routing, follow-up task creation, CRM cleanup support, Gmail draft creation, intake triage, reporting updates, or support-to-sales handoff.',
  },
  {
    q: 'Can you connect this to HubSpot or Salesforce?',
    a: 'Yes. Most of our automation work connects into CRM because that is where ownership, lifecycle stage, follow-up, reporting, and pipeline visibility need to live.',
  },
  {
    q: 'How do you avoid automation breaking things?',
    a: 'We build with logs, small batches, approval states, reversible changes, test records, and clear documentation. Automation should reduce risk, not hide it.',
  },
];

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  name: 'AI Automation Consulting',
  serviceType: 'AI workflow automation, n8n automation, and CRM automation consulting',
  provider: {
    '@type': 'Organization',
    name: 'Emergent Logic',
    url: 'https://www.emergent-logic.ca/',
  },
  areaServed: 'Canada',
  url: 'https://www.emergent-logic.ca/services/ai-automation-consulting',
  description: metadata.description,
};

export default function AIAutomationConsultingService() {
  return (
    <main className="min-h-screen">
      <Navbar />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      <section className="pt-32 pb-20 bg-gradient-to-br from-slate-950 via-violet-950 to-indigo-950">
        <div className="container mx-auto px-4 max-w-4xl">
          <div className="text-violet-100/70 text-sm mb-4">
            <Link href="/" className="hover:text-white">Home</Link> / <Link href="/#services" className="hover:text-white">Services</Link> / <span className="text-white">AI Automation Consulting</span>
          </div>
          <div className="inline-block px-3 py-1 rounded-full bg-white/10 text-violet-100 text-xs font-medium mb-4">
            Supporting service
          </div>
          <h1 className="text-4xl md:text-6xl font-bold text-white mb-6 leading-tight">
            AI Automation Consulting for Real Business Workflows
          </h1>
          <p className="text-xl text-white/80 mb-8 max-w-3xl">
            We design and build AI-assisted workflows that connect CRM, Gmail, Google Sheets, website forms, n8n, HubSpot, Salesforce, and human review. The goal is not automation theater. The goal is cleaner handoffs, faster follow-up, and fewer manual loops.
          </p>
          <div className="flex flex-col sm:flex-row gap-4">
            <TrackedCTA ctaName="Book a Free Strategy Call - AI Automation Hero" destination="calendly">
              <a href="https://calendly.com/emergent-logic/30min" target="_blank" rel="noopener noreferrer">
                <Button size="lg" className="bg-white text-violet-950 hover:bg-violet-100 font-semibold px-8">
                  Book a Free Strategy Call <ArrowRight className="w-5 h-5 ml-2" />
                </Button>
              </a>
            </TrackedCTA>
            <Link href="/case-studies/ai-revenue-operations-engine">
              <Button size="lg" className="bg-transparent border-2 border-white/40 text-white hover:bg-white/10 font-semibold px-8">
                View AI Revenue Ops Case Study
              </Button>
            </Link>
          </div>
          <div className="mt-8 flex flex-wrap gap-6 text-white/70 text-sm">
            <div className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-violet-200" /> 1 workflow at a time</div>
            <div className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-violet-200" /> n8n, CRM, Gmail, Sheets, APIs</div>
            <div className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-violet-200" /> Human approval gates</div>
            <div className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-violet-200" /> From $1,500</div>
          </div>
        </div>
      </section>

      <section className="py-12 bg-violet-50 border-b">
        <div className="container mx-auto px-4 max-w-4xl">
          <div className="flex items-start gap-4">
            <ShieldCheck className="w-8 h-8 text-violet-700 flex-shrink-0 mt-1" />
            <div>
              <h2 className="text-xl font-bold text-gray-900 mb-2">We automate the workflow, not the judgment.</h2>
              <p className="text-gray-700">
                The safest AI systems prepare, classify, summarize, route, and draft. Humans still approve sensitive actions, live sends, customer-facing decisions, and high-risk updates. That balance is how automation becomes useful without becoming reckless.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 max-w-4xl">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">What We Build</h2>
          <p className="text-lg text-gray-600 mb-8">
            We start with practical workflows that remove repeatable manual work and make your CRM more reliable.
          </p>
          <div className="grid md:grid-cols-2 gap-6">
            {automationTypes.map((item) => (
              <Card key={item.title} className="border shadow-sm">
                <CardContent className="p-6">
                  <item.icon className="w-8 h-8 text-violet-700 mb-4" />
                  <h3 className="text-xl font-bold text-gray-900 mb-2">{item.title}</h3>
                  <p className="text-gray-600">{item.desc}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4 max-w-4xl">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Our Build Sequence</h2>
          <p className="text-lg text-gray-600 mb-8">
            We do not start with a giant automation map. We start with one high-value workflow, make it reliable, then expand.
          </p>
          <div className="space-y-4">
            {processSteps.map((step, index) => (
              <div key={step} className="flex items-start gap-4 bg-white border rounded-xl p-5">
                <div className="w-9 h-9 rounded-full bg-violet-700 text-white flex items-center justify-center font-bold flex-shrink-0">
                  {index + 1}
                </div>
                <p className="text-gray-700 pt-1">{step}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 max-w-4xl">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Good Fit</h2>
          <div className="grid md:grid-cols-2 gap-4 mb-12">
            {goodFit.map((item) => (
              <div key={item} className="flex items-start gap-3 bg-gray-50 border rounded-xl p-5">
                <Check className="w-5 h-5 text-violet-700 flex-shrink-0 mt-0.5" />
                <p className="text-gray-700">{item}</p>
              </div>
            ))}
          </div>

          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Not a Good Fit</h2>
          <div className="grid md:grid-cols-2 gap-4">
            {notFit.map((item) => (
              <div key={item} className="flex items-start gap-3 bg-red-50 border border-red-100 rounded-xl p-5">
                <ShieldCheck className="w-5 h-5 text-red-700 flex-shrink-0 mt-0.5" />
                <p className="text-gray-700">{item}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4 max-w-4xl">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Timeline and Investment</h2>
          <p className="text-lg text-gray-600 mb-8">
            We scope around one workflow first. That keeps cost controlled and gives you a usable system quickly.
          </p>
          <div className="grid md:grid-cols-2 gap-8">
            <Card className="border bg-white">
              <CardContent className="p-8">
                <Clock className="w-10 h-10 text-violet-700 mb-4" />
                <h3 className="text-2xl font-bold text-gray-900 mb-2">1 to 4 Weeks</h3>
                <p className="text-gray-600">
                  Simple workflows can ship in a few days. CRM-connected, multi-step workflows with testing and documentation typically take 1 to 4 weeks.
                </p>
              </CardContent>
            </Card>
            <Card className="border bg-white">
              <CardContent className="p-8">
                <Workflow className="w-10 h-10 text-violet-700 mb-4" />
                <h3 className="text-2xl font-bold text-gray-900 mb-2">From $1,500 CAD</h3>
                <p className="text-gray-600">
                  Focused workflow builds start at $1,500. Larger systems involving multiple tools, CRM cleanup, enrichment, and reporting are scoped after discovery.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 max-w-4xl">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-8">Frequently Asked Questions</h2>
          <div className="space-y-6">
            {faqs.map((item) => (
              <Card key={item.q} className="border">
                <CardHeader>
                  <CardTitle className="text-lg">{item.q}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600">{item.a}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      <section className="py-12 bg-gray-50">
        <div className="container mx-auto px-4 max-w-4xl">
          <h3 className="text-xl font-bold text-gray-800 mb-4">Related Services and Resources</h3>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            <Link href="/case-studies/ai-revenue-operations-engine" className="block bg-white border rounded-xl p-4 hover:shadow-md transition-shadow">
              <p className="font-medium text-violet-700">AI Revenue Operations Case Study</p>
              <p className="text-gray-600 text-sm">How a guarded AI growth system can connect CRM, outbound, SEO, and social</p>
            </Link>
            <Link href="/services/ai-chatbot-automation" className="block bg-white border rounded-xl p-4 hover:shadow-md transition-shadow">
              <p className="font-medium text-violet-700">AI Chatbot Automation</p>
              <p className="text-gray-600 text-sm">A focused AI workflow for website lead qualification</p>
            </Link>
            <Link href="/services/crm-integration" className="block bg-white border rounded-xl p-4 hover:shadow-md transition-shadow">
              <p className="font-medium text-violet-700">CRM Integration</p>
              <p className="text-gray-600 text-sm">Connect automation output into CRM ownership and reporting</p>
            </Link>
            <Link href="/services/crm-cleanup" className="block bg-white border rounded-xl p-4 hover:shadow-md transition-shadow">
              <p className="font-medium text-violet-700">CRM Cleanup</p>
              <p className="text-gray-600 text-sm">Fix the data foundation before automating on top of it</p>
            </Link>
            <Link href="/blog/ai-chatbot-lead-qualification-crm" className="block bg-white border rounded-xl p-4 hover:shadow-md transition-shadow">
              <p className="font-medium text-violet-700">AI Chatbot CRM Guide</p>
              <p className="text-gray-600 text-sm">Why AI conversations need CRM routing and follow-up</p>
            </Link>
            <Link href="/lead-follow-up-audit" className="block bg-white border rounded-xl p-4 hover:shadow-md transition-shadow">
              <p className="font-medium text-violet-700">Lead Follow-Up Audit</p>
              <p className="text-gray-600 text-sm">Review one workflow before automating it</p>
            </Link>
          </div>
        </div>
      </section>

      <section className="py-20 bg-gradient-to-br from-violet-900 to-slate-950">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Have a Workflow You Want Automated?</h2>
          <p className="text-xl text-white/80 mb-8 max-w-2xl mx-auto">
            Book a free 30-minute strategy call. We will help identify the first workflow worth automating and tell you where automation would create more risk than value.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <TrackedCTA ctaName="Book Free Strategy Call - AI Automation Footer" destination="calendly">
              <a href="https://calendly.com/emergent-logic/30min" target="_blank" rel="noopener noreferrer">
                <Button size="lg" className="bg-white text-violet-950 hover:bg-violet-100 font-semibold px-8">
                  Book a Free Strategy Call <ArrowRight className="w-5 h-5 ml-2" />
                </Button>
              </a>
            </TrackedCTA>
            <Link href="/case-studies/ai-revenue-operations-engine">
              <Button size="lg" className="bg-transparent border-2 border-white/40 text-white hover:bg-white/10 font-semibold px-8">
                View Case Study
              </Button>
            </Link>
          </div>
        </div>
      </section>

      <Footer />
      <CookieConsent />
    </main>
  );
}
